### ISSUE TITLE
Servers list on the website doesn't match the one in Git

### ISSUE THREAD

**Issue by steven676** [compserv/hivemind#11]
The servers listed on the hivemind website include only eda-[1-4] despite backend/servers.txt being updated in the Git repository to include eda-[5-11] on January 18 -- did someone forget to update the actual backend?

**Comment by ochan1** [comment]
On behalf of CompServ, apologies for the wait
I went ahead and merged in your Pull Request https://github.com/compserv/hivemind/pull/10

eda5-11 statuses are up and running on hivemind now

Let us know if you have any questions
